### ISSUE TITLE
[Bug] after running npm run build, on the index.html file under the build folder shows blank screen

### ISSUE THREAD

**Issue by gregmoncayo** [creativetimofficial/material-dashboard-react#111]
### Version
1.0.0
### Reproduction link
https://github.com/gregmoncayo/React/tree/master/WebSite
### Operating System
Mac OS
### Device
Macbook air
### Browser & Version
Google chrome 79.0
### Steps to reproduce
1. In the json file, removed homepage: "https://www.creative-tim/etc" to homepage: ".",
2. Open terminal and npm run build
3. Open build folder and open index.html file
4. See blank screen and when inspect on google chrome console see two red errors:
- DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///admin/index' cannot be created in a document with origin 'null' and URL 
-Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///admin/index' cannot be created in a document with origin 'null' and URL 
### What is expected?
Expected it to run normally as if I npm run serve
### What is actually happening?
blank white screen with console log errors in google chrome

---
### Solution
I believe something is wrong in my json file when trying to build it, I just don't know what.

**Comment by EINazare** [comment]
Hello there, @gregmoncayo ,

Please delete the homepage prop altogether.
Also, the correct way to open the build folder is to run the `serve -s build` command.

Best,
Manu

**Comment by MigueVeliz** [comment]
> Hello there, @gregmoncayo ,
> 
> Please delete the homepage prop altogether.
> Also, the correct way to open the build folder is to run the `serve -s build` command.
> 
> Best,
> Manu

this worked for me. Thanks!

**Comment by shachardevops** [comment]
Same issue... still not working for me.
I saw that there is one css that failed to downloaD from cdn

**Comment by EINazare** [comment]
Hello there, @shachardevops ,

Please make a video with the following:

* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run `node -v`
* Run `npm -v`
* Run `npm install`
* Open package.json
* Delete the homepage prop
* Save changes (showcase this)
* Run `npm run build`
* Run `serve -s build`
* Open browser
* Navigate to [http://localhost:5000](http://localhost:5000)
* Showcase the errors that you get (the errors could be shown in the console of the browser, so be sure to use a browser that has a console)

Best,
Manu

**Comment by shachardevops** [comment]
thanks.
I removed the homepage prop from package.json and its working well.
my problem was i deleted the homepage prop from the bower.json

**Comment by gregmoncayo** [comment]
I am testing on how to deploy react applications and when I try to deploy it in AWS using Amplify, I received this error.
![image](https://user-images.githubusercontent.com/33080223/75466895-e314b280-5958-11ea-9341-d4824ef77e85.png)
This my build. I have also just left it as:
- npm i 
- npm run build
Have also used:
- npm i
- serve -s build
![image](https://user-images.githubusercontent.com/33080223/75466782-b3fe4100-5958-11ea-9b5f-001a62836bf5.png)

Is there a certain way you recommend deploying it?

**Comment by EINazare** [comment]
Hello there, @gregmoncayo ,

Unfortunately, we do not have any experience with AWS, and don't know how to guide you.
To deploy any of our React products, since they are create-react-app based, it should be as simple as the following tutorials:

- https://aws.amazon.com/getting-started/tutorials/deploy-react-app-cicd-amplify/
- https://medium.com/dailyjs/a-guide-to-deploying-your-react-app-with-aws-s3-including-https-a-custom-domain-a-cdn-and-58245251f081

If you are still having errors, maybe the issue comes from the homepage prop, which is set to point to the live preview of this product, and maybe you need to provide a homepage prop for your own domain, or you have to delete the homepage prop altogether.
Read more about homepage prop and deployment on the official ReactJS docs:

- https://create-react-app.dev/docs/deployment/
- https://create-react-app.dev/docs/deployment/#aws-amplify
- https://create-react-app.dev/docs/deployment/#step-1-add-homepage-to-packagejson

Let me know if that helped.

Best,
Manu
