### ISSUE TITLE
[Bug] Missing documentation for notifications

### ISSUE THREAD

**Issue by jbatx** [creativetimofficial/material-dashboard-react#120]
### Version
1.8.0
### Reproduction link
https://www.creative-tim.com/
### Operating System
Mac
### Device
laptop
### Browser & Version
chrome  81.0.4044.138
### Steps to reproduce
I bought the pro version this afternoon.  I got the LoginPage.js working with my API.  I'm now trying to show a notification on failed login.  I can't find any helpful docs on using the notification component that is demoed in the demo dashboard.   The closest thing I found is https://github.com/creativetimofficial/react-notification-alert which is out of date and uses a string ref.  I'm not actually sure if those docs are relevant to your notification component that I bought.  Please advise.  

PS. I'm fairly new to react.
### What is expected?
clear documentation explaining how to show a notification
### What is actually happening?
no doc

---
### Solution
none
### Additional comments
none

**Comment by EINazare** [comment]
Hello there, @jbatx ,

Thank you for your interest in working with our products.
Here is the docs on the Alerts used in the Material Dashboard PRO React product: https://demos.creative-tim.com/material-dashboard-pro-react/#/documentation/snackbar

I will close this issue, since it is not properly opened.

Best,
Manu
