### ISSUE TITLE
[Bug] TypeError: data.forEach is not a function

### ISSUE THREAD

**Issue by NealWalters** [creativetimofficial/material-dashboard-react#139]
### Version
1.9.0
### Reproduction link
https://jsfiddle.net/xgq72znb/
### Operating System
Windows 10
### Device
Desktop
### Browser & Version
Chrome Version 84.0.4147.135
### Steps to reproduce
I copied ReactTables.js to a new file called ViewTranslations.js.  I have implemented code to retrieve data from an API. 
When I put data as a variable [dataTable] in /variables/general.js the form appears and looks great. 
Then I tried to populate it with code that fetched that the data from a REST API and massaged it to product same JSON data as I had in general/js. 

I got some good suggestions here, and the debug log looks pretty good. 
https://stackoverflow.com/questions/63619129/material-ui-fetching-data-display-in-datatable-react-usestate-cannot-be-c/63619346?noredirect=1#comment112503867_63619346

### What is expected?
Data from REST API to appear in table same was as getting JSON from /variables/general.js 
### What is actually happening?
This contains output of the debug console.log in browser: 

https://www.evernote.com/l/ABB0UwTvbFdLjpbwzwqFEG6KezRKcN9K5zc/

---

**Comment by EINazare** [comment]
Hello again, @NealWalters ,

Unfortunately, this is not part of our support plan: https://www.creative-tim.com/support-terms
You can take a look at our tutorials, the ones that I've given you the other issue.
I believe you are not calling the API in the right manner, but since we have a limited idea of how an API works with React, we do not know what guidance to give to you.
Since this issue is already addressed by the Feature Request one, I'll close this one.
