### ISSUE TITLE
Failure to deploy production optimized build

### ISSUE THREAD

**Issue by ismail-a-khan** [creativetimofficial/material-dashboard-react#17]
I'm struggling to deploy even the free version of this template. I wanted to experiment with the free version before I purchased the Pro version, but I'm stuck on the free version so far :( 

Here are the steps: 

1. Download the template, unzip folder 
2. Run `npm install `
3. Run `npm start` --> everything works fine 
4. Run `npm run build`. This creates a build folder. 
5. Deploy build folder to Firebase Hosting. 
6. When I navigate to the URL I deployed to, I see the following error: 

`Uncaught SyntaxError: Unexpected token <`: `main.2eeed198.js:1` What's weird is that the linked JS 
file is not a JS file but actually an HTML file. Any idea how to fix it? I haven't made any modifications, this is all on the basic template!

**Comment by EINazare** [comment]
Hello @ismail-a-khan ,

Our team has not worked yet with firebase, we've only worked with github pages and heroku. 
I've done some quick search on the internet and found numerous tutorials on how to deploy react app to firebase. 
From my previous searches (searches product related), i've seen that tutorials from medium.com usually are good to follow, so i'm going to give you a tutorial from medium (once again, there are a lot of other tutorials):
- [medium tutorial]( https://medium.com/@bensigo/hosting-your-react-app-with-firebase-hosting-add1fa08c214)
(the firebase stuff is right at the end (search for "woo , almost") and start reading from there. 

Because today is Sunday, i am not at my desk to verify if this would work, so i'm going to wait for your response to see if everything works now. 

Best, Manu.

**Comment by web10** [comment]
Hi Manu,

Actually, I am having the same problem trying to deploy the free version of material dashboard on heroku, so if you know of a tutorial that can help me through it since your team has done it, I would appreciate it.  I have reached out to Heroku but they said this was an app issue and they cannot help.

Here's what I did, I cloned the material-dashboard free app from github
npm install
npm start //and it opens the app in the browser correctly.
heroku login credentials
heroku create // to prepare heroku space for the app
git add . 
git commit 
git push heroku master
heroku open

then it does open up the browser with the appname.herokuapp.com, and shows the ico file on the tab but the content window is blank, no app see.

Any idea where I went wrong? or if you know of a tutorial for me to follow, I'd appreciate it.

Danh Nguyen
