### ISSUE TITLE
Change color for a component

### ISSUE THREAD

**Issue by jaymathew** [creativetimofficial/material-dashboard-react#21]
Hello,  

I am working on a project that the primaryColor needs to change per user.  I have been looking at this project and for example in Task.jsx I see your passing in an object with different colors like 'checked: 'Tasks-checked-407"'.  How can I supply my own custom color here?  Is there a better way to change the primaryColor per user? 

Thanks

**Comment by EINazare** [comment]
Hello @jaymathew ,

To change the primary color of the whole project, you can change line 56 inside `src/assets/jss/material-dashboard-react.jsx` file (`const primaryColor = "#9c27b0";`). You say you want to have for each user a different color, you could change that line with something like:
```
function randomString(len, charSet) {
    charSet = charSet || 'ABCDEF0123456789';
    var randomString = '';
    for (var i = 0; i < len; i++) {
        var randomPoz = Math.floor(Math.random() * charSet.length);
        randomString += charSet.substring(randomPoz,randomPoz+1);
    }
    return randomString;
}

console.log(randomString(6));

const primaryColor = "#" + randomString(6);
```
And have a "random" generated color for each user. This is if you would like to change the primary color for the whole project.

If you want to change the primary color just for the checked state of the checkboxes inside the Tasks.jsx you could go inside `src/components/Tasks/Tasks.jsx` and immediately after line 16 (`import tasksStyle from "assets/jss/material-dashboard-react/tasksStyle.jsx";`) add something like:
```
function randomString(len, charSet) {
    charSet = charSet || 'ABCDEF0123456789';
    var randomString = '';
    for (var i = 0; i < len; i++) {
        var randomPoz = Math.floor(Math.random() * charSet.length);
        randomString += charSet.substring(randomPoz,randomPoz+1);
    }
    return randomString;
}

tasksStyle["checked"]["color"] = "#" + randomString(6);
```

Or you could add the random color inside `assets/jss/material-dashboard-react/tasksStyle.jsx` at line 49, instead of `color: primaryColor`, you would put `color: "#" + randomString(6)` and at the beginning of the file you would put the randomString function: 
```
function randomString(len, charSet) {
    charSet = charSet || 'ABCDEF0123456789';
    var randomString = '';
    for (var i = 0; i < len; i++) {
        var randomPoz = Math.floor(Math.random() * charSet.length);
        randomString += charSet.substring(randomPoz,randomPoz+1);
    }
    return randomString;
}
```

Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu
