### ISSUE TITLE
why is there no "CustomSelect"?

### ISSUE THREAD

**Issue by liuyingyyll** [creativetimofficial/material-dashboard-react#25]
I used the <Select> component from "material-ui", but the style is quite different from the custom style. Can anyone help?

**Comment by EINazare** [comment]
Hello @liuyingyyll ,

Thank you for your interest in using our products.
There is no CustomSelect because this is the free version of our product.
If you want CustomSelects, than you need the pro version: [Material Dashboard Pro React](https://www.creative-tim.com/product/material-dashboard-pro-react)

Best,
Manu
