### ISSUE TITLE
 serve -s build is not working

### ISSUE THREAD

**Issue by JesusFregoso** [creativetimofficial/material-dashboard-react#28]
i have a problem when running npm run-script build everythings works but when i run serve -s build the style seens to be broken whats the problem with that  
![image](https://user-images.githubusercontent.com/8525045/40450229-3e058cc2-5e98-11e8-8f71-d6697006d020.png)

so i want to deploy the react app with node js but i can't work with this build there is something i can do about it??

this is how it looks like in development enviroment 
![image](https://user-images.githubusercontent.com/8525045/40453920-0db9b3b6-5ea4-11e8-8dd9-3eaf3d03d073.png)

**Comment by EINazare** [comment]
Hello @JesusFregoso ,

I do not understand what the problem is. The thing is that we haven't `served` our react products. We've only run the build command and then we've deployed them on gh-pages, or on heroku. To be honest with you i do not know how to help you. When i'll have some spare time, i am going to take a look at this but until then, maybe the community will come with some answers.

Best,
Manu

**Comment by JesusFregoso** [comment]
I found the problem, i was looking at the dependecies ando i realiza that i
hace material-ui and @materia-ui, idk why but the vas clases that is
generated radom was overriding buenas material-ui. Well i chance everything
with @material-ui and now is working. Thanks you for doing such a great
work.

**Comment by villarama37** [comment]
Thanks @JesusFregoso.  I had the same issue and I didn't know how I was going to figure this out.
