### ISSUE TITLE
How can i force contents to fit height of screen?

### ISSUE THREAD

**Issue by EasonPai** [creativetimofficial/material-dashboard-react#30]
Thanks for your great works, having fun playing with it.

I have a 2 lists in right area, as one of the lists grows its size, the whole right area have to scroll. 

What I want is to keep all contents (2 lists in my case) to fit the screen height either when size grows or even no item in list at all.

<img width="616" alt="layout-control" src="https://user-images.githubusercontent.com/678352/40538526-88e0dfc8-6044-11e8-9cf4-f02568e75970.png">

**Comment by EINazare** [comment]
Hello @EasonPai ,

Thank you for your interest in using our products.
To make them be as the screen height, you should use on them `100vh` instead of `100%` (`heaight: 100vh`,) or you can add on the wrapper container of the two the property `height: 100vh` and on them `height: 100%`.

Hope that information helps you.

Best,
Manu.

**Comment by EasonPai** [comment]
Thanks for the help.

I know I can use `100vh`, I tried to put it in `appStyle/mainPanel` and `appStyle/content`, but they all take no effects and I am wondering what is the best practice on doing this in your design.

As your suggestion, if I put the style on my wrapper container of lists, then it works,
only I have to hardcoded a `calc(100vh - 133px)` on it, 
but it's fine if this the best way to do it.
