### ISSUE TITLE
Failed to compile when starting server

### ISSUE THREAD

**Issue by garettschultz** [creativetimofficial/material-dashboard-react#4]
Browser displays errors after starting the server with "npm start". Keeps saying "Failed to compile". 

Module not found: Can't resolve 'assets/css/material-dashboard-react.css' in '/home/user/Desktop/projects/project-folder/src'

Node/npm versions:
npm version - 5.6.0
Node version - 9.5.0
OS - Linux Mint

**Comment by EINazare** [comment]
Hello @garettschultz ,

Thank you for your interest in our product.
The problem is that it does not read the .env file. To do this, you can choose one of the following:

1. Change NODE_PATH=src to NODE_PATH=./src inside .env file; 
2. Change "react-scripts start" to "cross-env NODE_PATH=./src react-scripts start" inside package.json ; 
3. npm install -g cross-env ;

I would suggest that you do the third option, and that is because all our products will have the same configuration, and if you will work with other of our products, they will also get this error and you would have to make one of options 1 or 2 always. If you do the third option, the .env file will be taken in consideration on start.

Best,
Manu

**Comment by garettschultz** [comment]
Thanks for the response. So if I was going to use your components, which option would be best to use out of those 3?


-------- Original message --------

**Comment by EINazare** [comment]
You should go with the third one.

Manu

**Comment by garettschultz** [comment]
Okay, thanks for such a quick reply. Appreciate the support.


-------- Original message --------

**Comment by MagnusBrzenk** [comment]
This info would have been really useful in the readme; I just wanted a super quick start but had to spend time figuring out that `NODE_PATH=src SKIP_PREFLIGHT_CHECK=true npm run start` is what you need to get stuff going asap
