### ISSUE TITLE
Convert to typescript 

### ISSUE THREAD

**Issue by crashnick16** [creativetimofficial/material-dashboard-react#5]
I am looking to convert this template to typescript but I did not manage to get it working yet.

I started off with ChartCard.jsx file but I keep getting errors like:

 Type '{ card: { display: string; position: string; width: string; margin: string; boxShadow: string; bo...' provides no match for the signature '(theme: Theme): Record<"card" | "cardHeader" | "cardTitle" | "cardContent" | "cardCategory" | "cardStats" | "cardActions" | "cardStatsLink" | "cardStatsIcon" | "orangeCardHeader" | "greenCardHeader" | "redCardHeader" | "blueCardHeader" | "purpleCardHeader" | "warningCardStatsIcon" | "primaryCardStatsIcon" | "dangerCardStatsIcon" | "successCardStatsIcon" | "infoCardStatsIcon" | "roseCardStatsIcon" | "grayCardStatsIcon", CSSProperties>'.

Any ideas?

Thanks,
Nick

**Comment by Slessi** [comment]
@crashnick16 @EINazare I have ported version 1.2.0 of this project to TypeScript at https://github.com/Slessi/material-dashboard-react-ts if either of you are interested

It is worth noting that there are some slight changes to dependencies, mostly notably using `@material-ui/core#^1.0.0` instead of the beta version used in 1.2.0. Other lib versions were prefixed with `^`.

Only issue I noticed was the card header clipping mentioned in #26 but I fixed it with `overflow: visible` in JSS.

**Comment by EINazare** [comment]
Hello @Slessi ,

Thank you for this.
I am going to make an update to `@material-ui/core` at the end of this week and i am going to take a look at your code to see if i can somehow integrate it in our product.

Once again thank you,
Manu

**Comment by Slessi** [comment]
Cool, drop a message if you have any questions :)

**Comment by kmturley** [comment]
This dashboard project is also written in typescript:
https://github.com/goemen/react-material-ui-typescript

**Comment by iamandrewluca** [comment]
There is no need to rewrite all project in TypeScript, better to add definition types near components, or other files that are used, or create the definitions separately in https://github.com/DefinitelyTyped/DefinitelyTyped
