### ISSUE TITLE
Can I dynamicaly set the variable data from a google sheet? 

### ISSUE THREAD

**Issue by pereiraryan** [creativetimofficial/material-dashboard-react#51]
Is there a way to set the variable data in the dashboard from a sheet or an api call ?

**Comment by EINazare** [comment]
Hello @pereiraryan ,

And thank you for your interest in using our product.
I do not understand your question, i do not know what data variable are you asking.
But since this is a free product, you can download it from here or from [www.creative-tim.com](www.creative-tim.com) and do some tests and see if you can do what you are asking.
Once again, i am sorry for not understanding your question.

Best,
Manu

**Comment by kdclaw3** [comment]
@pereiraryan Hey Ryan, 

I have an example on the fork of this project. I did a small modification to call a weather api and update the chart... see the code here https://github.com/kdclaw3/material-dashboard-react/commit/c5958371312a12dfb4bb3b0e534ec55a5a5464f9

You can use it off the api_call branch if you want...
https://github.com/kdclaw3/material-dashboard-react/tree/apicall_example

**Comment by pereiraryan** [comment]
Hey @kdclaw3  is this possible to get it done by a google sheet as well?
