### ISSUE TITLE
Having Trouble understanding your project structure.........

### ISSUE THREAD

**Issue by THEMESSINHO** [creativetimofficial/material-dashboard-react#53]
I have created a folder in views directory and created a file named crd.jsx.Then I have added following url object in dashboardRoutes array 
{ path: "/card", sidebarName: "cardexample", navbarName: "Material Card", icon: Dashboard, component: CardBasic1 }
[crd.txt](https://github.com/creativetimofficial/material-dashboard-react/files/2205757/crd.txt)
after going to the url I am also getting the vertical navbar , search option ,notification icon.But i am not understanding why r they appearing.....In my crd.jsx which function is responsible for loading these components....

**Comment by EINazare** [comment]
Hello @THEMESSINHO ,

I believe we have spoken and asked you to open this issue due to the fact that i did not understand where the code was, and where the issue question was.
That is happening because the crd.jsx is rendered inside the dashboardRoutes, which means it will render inside the src/layouts/Dashboard/Dashboard.jsx which has the sidebar, navbar and footer i believe. 
If you do not want this to happen, then you either create a new layout and add that layout in src/routes/index.jsx , and then create a new route file for that layout, or you can simply move the route you have made, inside src/routes/index.jsx without any layout.

Best,
Manu
