### ISSUE TITLE
Editing the color palette / style globally

### ISSUE THREAD

**Issue by Wintereise** [creativetimofficial/material-dashboard-react#90]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

I'm a material dashboard react pro subscriber **with current premium support.**

It would appear that every single value for the color palette is hardcoded RGB, this has been reported once before by @vbartusevicius in https://github.com/creativetimofficial/material-dashboard-react/issues/66

The issue has a trivial fix, which would be making use of https://material-ui.com/customization/themes/#theme-provider along with https://material-ui.com/style/color/

Instead of doing this, the palette appears to be hardcoded which makes customization in any dynamic way very difficult to achieve.

Last time, you responded that currently this was not in the roadmap. Has that changed?

**Comment by EINazare** [comment]
Hello there, @Wintereise ,

Thank you for your interest in working with our products.
You will find all of our colors here: `src/assets/jss/material-dashboard-react.jsx`, between lines 73 and 92. We didn't make use of the theme provider since some of our clients did not like the fact that the boxShadows were using the same colors as the states colors, but in rgba.
For example, in the past we had
```
const primaryColor = "#9c27b0";
```
and 
```
const primaryBoxShadow = {
  boxShadow:
    "0 12px 20px -10px rgba(156, 39, 176, 0.28), 0 4px 20px 0px rgba(0, 0, 0, 0.12), 0 7px 8px -5px rgba(156, 39, 176, 0.2)"
};
```
As you can see, `rgba(156, 39, 176, 0.2)` (or, more accurate `rgb(156, 39, 176)`), is the same color as `#9c27b0`. And this is kind of unacceptable, since if you change the primary color, you would also have to change this box shadow.
So what we've done, was to create a function `hexToRgb`, that transforms a hex to an RGB. So when you change the primary color variable, it automatically changes the box shadow as well (you do not have to make two changes, only one is required now).
So now the above code looks like:
```
// we have different variations of the primary color used along the product
const primaryColor = ["#9c27b0", "#ab47bc", "#8e24aa", "#af2cc5"];
```
```
const primaryBoxShadow = {
  boxShadow:
    "0 4px 20px 0 rgba(" +
    hexToRgb(blackColor) +
    ",.14), 0 7px 10px -5px rgba(" +
    hexToRgb(primaryColor[0]) +
    ",.4)"
};
```
As said above, now, if you change the first primary colors, it will change the primary box shadow as well, and everywhere you have `primaryColor[0]`. Once again, this was a request by many of our clients, on both the PRO and the FREE products, as well as the KIT's ones.
If we were to make use of the theme provider, we would have to revert back to the old way, i.e, we would have something like this:
```
...
primaryColor: "#9c27b0"
...
primaryBoxShadow: "0 12px 20px -10px rgba(156, 39, 176, 0.28), 0 4px 20px 0px rgba(0, 0, 0, 0.12), 0 7px 8px -5px rgba(156, 39, 176, 0.2)"
```
Which will make our clients once again frustrated.
For the moment, I believe this is the best way to make our product as customizable as we can.

I have although one question, you say something about the PRO version in your comment, you also checked the `I'm reporting the issue to the correct repository (for multi-repository projects)`. Why did you open this issue here, and not on the PRO repository?

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by Wintereise** [comment]
Hey @EINazare,

Thanks for explaining why you had to do it. The thing is though, there's no reason you couldn't maintain this collection of 4 primary colors using the MUIThemeProvider as well.

See https://github.com/mui-org/material-ui/blob/0912310353382afea946ff57eaee7085c1479b2e/packages/material-ui/src/styles/createMuiTheme.js#L45

Basically, it'll pass in anything you place in the ThemeOptions -> palette: PaletteOptions property. Using this, you could do:

```
{ palette { primary: { main: <whatever>, shades: [ every single shade you need ] } } }
```

In fact, if you're worried about that augmentColors call (which does things like figuring out light/dark/contrastText if not provided), there's no reason this has to under the primary color at all.

Your 
```
const primaryBoxShadow = {
  boxShadow:
    "0 4px 20px 0 rgba(" +
    hexToRgb(blackColor) +
    ",.14), 0 7px 10px -5px rgba(" +
    hexToRgb(primaryColor[0]) +
    ",.4)"
};
``` 

example would simply be 

```
const primaryBoxShadow = theme => ({
  boxShadow:
    "0 4px 20px 0 rgba(" +
    hexToRgb(theme.palettes.black.main) +
    ",.14), 0 7px 10px -5px rgba(" +
    hexToRgb(theme.palettes.primary.shades[0]) +
    ",.4)"
});
```

The real downside for this is that you now have to use the withStyles HoC EVERYWHERE, but we made peace with that the moment we chose to work with mui, I think.

This is how we made it dynamic, works great for on the fly theme updates backed by a redux store. HTH.

**Comment by EINazare** [comment]
Hello again, @Wintereise ,

I wanted to write that in my last comment and forgot about it.
The problem is that now you use the theme provider, but you also need to keep variables like 
```
const primaryBoxShadow = theme => ({
  boxShadow:
    "0 4px 20px 0 rgba(" +
    hexToRgb(theme.palettes.black.main) +
    ",.14), 0 7px 10px -5px rgba(" +
    hexToRgb(theme.palettes.primary.shades[0]) +
    ",.4)"
});
```
Isn't this a bit frustrating?
This being said, we try to make all of our customers happy with the product they get. We'll see what we can do about this in our next updates - I can't promise you that we'll add the theme provider in our very next update, once again due to the time-consuming. Hope you understand us.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by Wintereise** [comment]
Hi,

It's all good, just a suggestion. We went with named shades instead that signify purpose instead of just an array.

Since you have full control over the injection context, you can pretty much do anything.
