### ISSUE TITLE
Legacy Context API / findDomNode usage

### ISSUE THREAD

**Issue by Wintereise** [creativetimofficial/material-dashboard-react#91]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

I'm a material dashboard react pro subscriber **with current premium support.**

The theme (thanks to material-ui 3.x usage) makes use of the legacy context API (which has been marked as deprecated) and findDomNode, both of which cause problems if one turns on React's `StrictMode` and are marked for removal sometime in the future.

material-ui is going to be fixing these in their 4.x release, will this theme be seeing that update?

Relevant MUI issues.

0. https://github.com/mui-org/material-ui/issues/14415
1. https://github.com/mui-org/material-ui/issues/13394

**Comment by EINazare** [comment]
Hello again, @Wintereise  ,

Yes, we are going to update our products to the v4 of Material-UI. But you have to understand, and I am not trying to be rude here, I am just trying to explain how we work at Creative-Tim - no offense intended, that beside this project, we have 11 other products that we also have to maintain, and also, while doing this we have to work on developing new products.
Since the React Material products are our most downloaded and used, we try to keep them as updated as we can, but once again, we can't neglect our other products. 
We expect that after Material-UI releases version 4, we are going to update all of our products in about 
1-3 months, and this is because we have 4 Material products and from our knowledge, Material-UI v4 will have a lot of major changes, for example, they are going to drop the usage of jss, and use [emotion](https://material-ui.com/guides/interoperability/#emotion) - this means that we'll also have to change our jss to emotion.

I hope I've asked your question.

I have although one question, you say something about the PRO version in your comment, you also checked the I'm reporting the issue to the correct repository (for multi-repository projects). Why did you open this issue here, and not on the PRO repository?

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by crimsonvspurple** [comment]
In the next major update, please develop with React strict mode.

**Comment by Wintereise** [comment]
Hey @EINazare,

> Yes, we are going to update our products to the v4 of Material-UI. But you have to understand, and I am not trying to be rude here, I am just trying to explain how we work at Creative-Tim - no offense intended, that beside this project, we have 11 other products that we also have to maintain, and also, while doing this we have to work on developing new products.

Fair enough, my intention wasn't to ask "why hasn't it been done yet (doing it already makes no sense, mui v4 is beta software),' but simply to understand if CT had plans to do so.

Regarding the challenges to do so, I fully understand. Thank you for providing the timeline.

> I have although one question, you say something about the PRO version in your comment, you also checked the I'm reporting the issue to the correct repository (for multi-repository projects). Why did you open this issue here, and not on the PRO repository?

That would be because I infact did not know that mdr had multiple repos. I googled it, found this repo, opened issues, found the other one afterwards ┐(´∀｀)┌ﾔﾚﾔﾚ

**Comment by EINazare** [comment]
> In the next major update, please develop with React strict mode.

Ok, so then it will take us more than 1-3 months. I'll discuss this with our board.

**Comment by EINazare** [comment]
Hello again, @Wintereise ,

> That would be because I infact did not know that mdr had multiple repos. I googled it, found this repo, opened issues, found the other one afterwards ┐(´∀｀)┌ﾔﾚﾔﾚ

You can get the right repo link from our website (from the comments section on the product page), or from our live docs.

**Comment by Flixbox** [comment]
> they are going to drop the usage of jss, and use emotion - this means that we'll also have to change our jss to emotion.

Do you have a source on that? According to the [blog post](https://material-ui.com/blog/material-ui-v4-is-out/) We can pretty much still use JSS logic with hooks.

**Comment by EINazare** [comment]
> > they are going to drop the usage of jss, and use emotion - this means that we'll also have to change our jss to emotion.
> 
> Do you have a source on that? According to the [blog post](https://material-ui.com/blog/material-ui-v4-is-out/) We can pretty much still use JSS logic with hooks.

I do not remember where I read that.
